# Generated by Django 5.0.4 on 2024-05-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stateprice',
            name='product',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='StatePrice',
        ),
    ]
