# Generated by Django 5.0.4 on 2024-04-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateprice',
            name='price',
            field=models.FloatField(),
        ),
    ]
