# Generated by Django 5.0.3 on 2024-04-02 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_llusergroup_lluserpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, default=None, max_length=250, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('locality', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('is_customer', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
