# Generated by Django 5.0.3 on 2024-04-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_customer_user_user_alter_seller_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_user',
            name='user',
        ),
    ]
