# Generated by Django 5.0.3 on 2024-04-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0008_seller_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('spirits', 'Spirits'), ('wines', 'Wines'), ('beers', 'Beers'), ('more', 'More')], max_length=20)),
                ('subcategory', models.CharField(blank=True, choices=[], max_length=20, null=True)),
                ('spirits_type', models.CharField(blank=True, choices=[], max_length=20, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.seller_user')),
            ],
        ),
    ]
