# Generated by Django 5.0.3 on 2024-04-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
