# Generated by Django 5.0.4 on 2024-04-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
