# Generated by Django 5.0.4 on 2024-04-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
