# Generated by Django 5.0.4 on 2024-05-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_sub_category',
        ),
    ]
