# Generated by Django 5.0.4 on 2024-05-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_remove_product_sub_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
