# Generated by Django 5.0.4 on 2024-05-24 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_product_sub_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_90ml', models.FloatField(blank=True, null=True)),
                ('size_180ml', models.FloatField(blank=True, null=True)),
                ('size_375ml', models.FloatField(blank=True, null=True)),
                ('size_750ml', models.FloatField(blank=True, null=True)),
                ('size_1ltr', models.FloatField(blank=True, null=True)),
                ('size_2000ml', models.FloatField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='size_price', to='seller.product')),
            ],
        ),
    ]
