# Generated by Django 5.0.4 on 2024-05-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_sizeprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SizePrice',
        ),
    ]
